alter table PROJECT_REPAIR add constraint FK_PROJECT_REPAIR_ON_CAR_SERVICE foreign key (CAR_SERVICE_ID) references PROJECT_CAR_SERVICE(ID);
alter table PROJECT_REPAIR add constraint FK_PROJECT_REPAIR_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PROJECT_EMPLOYEE(ID);
create index IDX_PROJECT_REPAIR_ON_CAR_SERVICE on PROJECT_REPAIR (CAR_SERVICE_ID);
create index IDX_PROJECT_REPAIR_ON_EMPLOYEE on PROJECT_REPAIR (EMPLOYEE_ID);
