alter table PROJECT_EMPLOYEE add constraint FK_PROJECT_EMPLOYEE_ON_CAR_SERVICE foreign key (CAR_SERVICE_ID) references PROJECT_CAR_SERVICE(ID);
create index IDX_PROJECT_EMPLOYEE_ON_CAR_SERVICE on PROJECT_EMPLOYEE (CAR_SERVICE_ID);
