-- begin PROJECT_CAR_SERVICE
alter table PROJECT_CAR_SERVICE add constraint FK_PROJECT_CAR_SERVICE_ON_CITY foreign key (CITY_ID) references PROJECT_CITY(ID)^
create index IDX_PROJECT_CAR_SERVICE_ON_CITY on PROJECT_CAR_SERVICE (CITY_ID)^
-- end PROJECT_CAR_SERVICE
-- begin PROJECT_EMPLOYEE
alter table PROJECT_EMPLOYEE add constraint FK_PROJECT_EMPLOYEE_ON_CAR_SERVICE foreign key (CAR_SERVICE_ID) references PROJECT_CAR_SERVICE(ID)^
create index IDX_PROJECT_EMPLOYEE_ON_CAR_SERVICE on PROJECT_EMPLOYEE (CAR_SERVICE_ID)^
-- end PROJECT_EMPLOYEE
-- begin PROJECT_REPAIR
alter table PROJECT_REPAIR add constraint FK_PROJECT_REPAIR_ON_CAR_SERVICE foreign key (CAR_SERVICE_ID) references PROJECT_CAR_SERVICE(ID)^
alter table PROJECT_REPAIR add constraint FK_PROJECT_REPAIR_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references PROJECT_EMPLOYEE(ID)^
create index IDX_PROJECT_REPAIR_ON_CAR_SERVICE on PROJECT_REPAIR (CAR_SERVICE_ID)^
create index IDX_PROJECT_REPAIR_ON_EMPLOYEE on PROJECT_REPAIR (EMPLOYEE_ID)^
-- end PROJECT_REPAIR
-- begin TEST_CLIENT_LINK
alter table TEST_CLIENT_LINK add constraint FK_TESCLI_ON_CAR_SERVICE foreign key (CAR_SERVICE_ID) references PROJECT_CAR_SERVICE(ID)^
alter table TEST_CLIENT_LINK add constraint FK_TESCLI_ON_CLIENT foreign key (CLIENT_ID) references PROJECT_CLIENT(ID)^
-- end TEST_CLIENT_LINK
-- begin PROJECT_LEGAL_PERSON
alter table PROJECT_LEGAL_PERSON add constraint FK_PROJECT_LEGAL_PERSON_ON_ID foreign key (ID) references PROJECT_CLIENT(ID) on delete CASCADE^
-- end PROJECT_LEGAL_PERSON
-- begin PROJECT_PHYSICAL_PERSON
alter table PROJECT_PHYSICAL_PERSON add constraint FK_PROJECT_PHYSICAL_PERSON_ON_ID foreign key (ID) references PROJECT_CLIENT(ID) on delete CASCADE^
-- end PROJECT_PHYSICAL_PERSON
-- begin PROJECT_CITY
create unique index IDX_PROJECT_CITY_UK_NAME on PROJECT_CITY (NAME) where DELETE_TS is null ^
-- end PROJECT_CITY
